### ISSUE TITLE
$HOSTNAME includes user

### ISSUE THREAD

**Issue by mbr** [rollcat/judo#6]
I stumbled across judo while writing basically the same thing as a shell script and I am very happy someone else did the work already, awesome job!

I have one question that, in my opinion, should either be addressed in the `readme.md` or added as a feature: How to handle different usernames on remote hosts?

Typically my hosts have a user account (`root` or something else) different from my personal user account on my local machine. This is guaranteed to be true when sharing devops tasks with team members, since we do not create an account for every team member on each host.

A workaround (if it is a workaround) has been to just put

```
root@somehost.example.com
```

into the group files, however this results in `root@` being part of `$HOSTNAME`:

```console
$ judo -c 'echo Hi from ${HOSTNAME}' all
Running: [root@somehost.example.com]
root@somehost.example.com: Hi from root@somehost.example.com
Success: [root@somehost.example.com]
```

I am aware that I could configure the user using an SSH config, but I would rather keep all the necessary connection info (sans private keys) in one place - is this something that could become part of judo?

**Comment by mbr** [comment]
For the moment, I have worked around this by creating an `ssh` wrapper script that sets `-F ssh_config` option, which also lets me customize `known_hosts`, ports, etc. This is a decent alternative, although it requires creating said wrapper.

**Comment by rollcat** [comment]
Handling per-host configuration options such as usernames, port numbers, proxy hosts, shoe size, first day of week, etc is an explicit non-goal, and I think [the readme](https://github.com/rollcat/judo#using-the-ssh-transport-without-abusing-it) is rather clear on this. If we support one "special" case (like user name), it would establish an ugly precedent, with the logical conclusion being having to support **all** of them.

In fact, I'm surprised adding a user name works at all (see #4, shasderias made a change to stop `scp` from complaining, while perhaps breaking IPv6 hostnames). I'd rather add code to explicitly reject it - it's not a part of the host name; you write `Host example.com` and not `Host user@example.com` in your config.

Judo could support an `-F ssh_config` flag, and pass it along to all invocations of `ssh`/`scp` - I think that would be a very explicit way of saying, "do this special very different thing, for this invocation only", and if you had some problem running `judo -F my_config ...` but not `judo ...`, then running `ssh -F my_config ...` would help reveal it. I would accept a PR adding this.
